[[redirects]]
from = "/programacion"
to = "/"
status = 301
force = true

[[redirects]]
from = "/ponentes"
to = "/"
status = 301
force = true

[[redirects]]
from = "/paquetes"
to = "/"
status = 301
force = true